version: '3.7'

services:
  dev:
    build:
      context: .
    environment:
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - 4680:3000
    command: npm start

  test:
    build:
      context: .
    environment:
      - CI=true
    command: npm test
    volumes:
      - './:/usr/src/app'