# App Properties
bezkoder:
  app:
    jwtSecret: bezKoderSecretKey
    jwtExpirationMs: 86400000

server:
  port: 9091

spring:
  datasource:
    initialization-mode: always
    platform: postgres
    url: jdbc:postgresql://localhost:5433/dndtools
    username: dndtools
    password: dndtools
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creatio:true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update