# App Properties
bezkoder:
  app:
    jwtSecret: bezKoderSecretKey
    jwtExpirationMs: 86400000

#spring:
#  data:
#    mongodb:
#      host: api-database
#      database: dnd-tools
#      username: dndtoolsadmin
#      password: 58dndtoolsadmin12
#      port: 27017
#  mongo:
#    repositories:
#      enabled: true

