version: "3.8"

networks:
  default:
    name: backend
services:
  api:
    image: dnd-tools-api
    environment:
      WAIT_HOSTS: api-database:27017
    ports:
      - 9091:8080
    links:
      - api-database
  api-database:
    image: mongo:3.6.23
    container_name: "api-database"
    environment:
      MONGO_INITDB_ROOT_USERNAME: dndtoolsadmin
      MONGO_INITDB_ROOT_PASSWORD: 58dndtoolsadmin12
      MONGO_INITDB_DATABASE: dnd-tools
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      #- ./data:/data/db
      - d:\/projects\/mongodb:/data/db
    ports:
      - 27017:27017
    command: --smallfiles

